FROM ubuntu:14.04
# include/install the list of allowed languages here


# install grading mechanism here


# create and set the user
RUN useradd -m -s /bin/bash jjeuser
USER jjeuser
WORKDIR /home/jjeuser

# retrieve the code/output to be graded

# run the grading mechanism on the retrieved files



#####
# Clarify:
# Should we build a single image that runs everything, or build a new image for submission?
#####
